#!/bin/sh
#
# Mount / ubifs as read-only be default
#

case "$1" in
  start)
        mount -o ro,remount /
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
